/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Example_H
#define Example_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "example_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ExampleIf {
 public:
  virtual ~ExampleIf() {}
  virtual void ping() = 0;
  virtual int32_t add(const int32_t a, const int32_t b) = 0;
};

class ExampleIfFactory {
 public:
  typedef ExampleIf Handler;

  virtual ~ExampleIfFactory() {}

  virtual ExampleIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ExampleIf* /* handler */) = 0;
};

class ExampleIfSingletonFactory : virtual public ExampleIfFactory {
 public:
  ExampleIfSingletonFactory(const ::std::shared_ptr<ExampleIf>& iface) : iface_(iface) {}
  virtual ~ExampleIfSingletonFactory() {}

  virtual ExampleIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ExampleIf* /* handler */) {}

 protected:
  ::std::shared_ptr<ExampleIf> iface_;
};

class ExampleNull : virtual public ExampleIf {
 public:
  virtual ~ExampleNull() {}
  void ping() {
    return;
  }
  int32_t add(const int32_t /* a */, const int32_t /* b */) {
    int32_t _return = 0;
    return _return;
  }
};


class Example_ping_args {
 public:

  Example_ping_args(const Example_ping_args&);
  Example_ping_args& operator=(const Example_ping_args&);
  Example_ping_args() {
  }

  virtual ~Example_ping_args() noexcept;

  bool operator == (const Example_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Example_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Example_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Example_ping_pargs {
 public:


  virtual ~Example_ping_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Example_ping_result {
 public:

  Example_ping_result(const Example_ping_result&);
  Example_ping_result& operator=(const Example_ping_result&);
  Example_ping_result() {
  }

  virtual ~Example_ping_result() noexcept;

  bool operator == (const Example_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Example_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Example_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Example_ping_presult {
 public:


  virtual ~Example_ping_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Example_add_args__isset {
  _Example_add_args__isset() : a(false), b(false) {}
  bool a :1;
  bool b :1;
} _Example_add_args__isset;

class Example_add_args {
 public:

  Example_add_args(const Example_add_args&);
  Example_add_args& operator=(const Example_add_args&);
  Example_add_args() : a(0), b(0) {
  }

  virtual ~Example_add_args() noexcept;
  int32_t a;
  int32_t b;

  _Example_add_args__isset __isset;

  void __set_a(const int32_t val);

  void __set_b(const int32_t val);

  bool operator == (const Example_add_args & rhs) const
  {
    if (!(a == rhs.a))
      return false;
    if (!(b == rhs.b))
      return false;
    return true;
  }
  bool operator != (const Example_add_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Example_add_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Example_add_pargs {
 public:


  virtual ~Example_add_pargs() noexcept;
  const int32_t* a;
  const int32_t* b;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Example_add_result__isset {
  _Example_add_result__isset() : success(false) {}
  bool success :1;
} _Example_add_result__isset;

class Example_add_result {
 public:

  Example_add_result(const Example_add_result&);
  Example_add_result& operator=(const Example_add_result&);
  Example_add_result() : success(0) {
  }

  virtual ~Example_add_result() noexcept;
  int32_t success;

  _Example_add_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Example_add_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Example_add_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Example_add_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Example_add_presult__isset {
  _Example_add_presult__isset() : success(false) {}
  bool success :1;
} _Example_add_presult__isset;

class Example_add_presult {
 public:


  virtual ~Example_add_presult() noexcept;
  int32_t* success;

  _Example_add_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ExampleClient : virtual public ExampleIf {
 public:
  ExampleClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ExampleClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  int32_t add(const int32_t a, const int32_t b);
  void send_add(const int32_t a, const int32_t b);
  int32_t recv_add();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ExampleProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<ExampleIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ExampleProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_add(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ExampleProcessor(::std::shared_ptr<ExampleIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &ExampleProcessor::process_ping;
    processMap_["add"] = &ExampleProcessor::process_add;
  }

  virtual ~ExampleProcessor() {}
};

class ExampleProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ExampleProcessorFactory(const ::std::shared_ptr< ExampleIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< ExampleIfFactory > handlerFactory_;
};

class ExampleMultiface : virtual public ExampleIf {
 public:
  ExampleMultiface(std::vector<std::shared_ptr<ExampleIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ExampleMultiface() {}
 protected:
  std::vector<std::shared_ptr<ExampleIf> > ifaces_;
  ExampleMultiface() {}
  void add(::std::shared_ptr<ExampleIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  int32_t add(const int32_t a, const int32_t b) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->add(a, b);
    }
    return ifaces_[i]->add(a, b);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ExampleConcurrentClient : virtual public ExampleIf {
 public:
  ExampleConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  ExampleConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  int32_t add(const int32_t a, const int32_t b);
  int32_t send_add(const int32_t a, const int32_t b);
  int32_t recv_add(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
